### ISSUE TITLE
[META] Integrate into tree

### ISSUE THREAD

**Issue by linclark** [bgrins/console-output-experiment#35]
- [ ] Demonstrate that we can do this in tree with a proof of concept patch (@bgrins)
- [ ] Test the impact using the Talos tests
- [ ] Develop mocha tests for Date component

---

- [ ]
